<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Sales\Block\Order\Info */ ?>
<?php $_order = $block->getOrder() ?>
<div class="block block-order-details-view">
    <div class="block-title">
        <strong><?= $block->escapeHtml(__('Order Information')) ?></strong>
    </div>
    <div class="block-content">
        <?php if (!$_order->getIsVirtual()) : ?>
        <table style="widtd:100%">
            <tr>
                <td>    <div class="box box-order-shipping-address">
                        <strong class="box-title"><span><?= $block->escapeHtml(__('Shipping Address')) ?></span></strong>
                        <div class="box-content">
                            <address><?= /* @noEscape */ $block->getFormattedAddress($_order->getShippingAddress()) ?></address>
                        </div>
                    </div>
                </td>
                <td> <div class="box box-order-shipping-metdod">
                        <strong class="box-title">
                            <span><?= $block->escapeHtml(__('Shipping Metdod')) ?></span>
                        </strong>
                        <div class="box-content">
                            <?php if ($_order->getShippingDescription()) : ?>
                                <?= $block->escapeHtml($_order->getShippingDescription()) ?>
                            <?php else : ?>
                                <?= $block->escapeHtml(__('No shipping information available')) ?>
                            <?php endif; ?>
                        </div>
                    </div></td>




        <?php endif; ?>
                <td> <div class="box box-order-billing-address">
                        <strong class="box-title">
                            <span><?= $block->escapeHtml(__('Billing Address')) ?></span>
                        </strong>
                        <div class="box-content">
                            <address><?= /* @noEscape */ $block->getFormattedAddress($_order->getBillingAddress()) ?></address>
                        </div>
                    </div></td>
                <td>  <div class="box box-order-billing-metdod">
                        <strong class="box-title">
                            <span><?= $block->escapeHtml(__('Payment Metdod')) ?></span>
                        </strong>
                        <div class="box-content">
                            <?= $block->getPaymentInfoHtml() ?>
                        </div>
                    </div></td>

            </tr>
        </table>
    </div>
</div>
